"""Every typed property and request ``TypedDict`` key must exist in the OpenAPI schema of its
route, or be listed below as a divergence proven on the wire (with its evidence).

The schema keys come from ``tests/fixtures/spec-keys.json``, generated by
``scripts/spec_keys.py`` from ``nfeio-docs/static/api`` (anchored on paths, not operationIds).
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

from nfeio import models, types
from nfeio.models._base import NfeObject, iter_fields

ROOT = Path(__file__).resolve().parents[2]
SPEC_KEYS: dict[str, list[str]] = json.loads(
    (ROOT / "tests" / "fixtures" / "spec-keys.json").read_text("utf-8")
)["keys"]

#: Wire keys missing from the spec but observed on the wire (design §16).
PROVEN_DIVERGENCES: dict[str, dict[str, str]] = {
    "Certificate": {
        "providerType": "SONDA 2026-10-08 §5 / design §16 #23 — present in every certificate",
        "expiresOn": "SONDA §4 / design §16 #24 — companies list uses expiresOn, not validUntil",
    },
}

MODEL_SCHEMAS: dict[type[NfeObject], list[str]] = {
    models.ServiceInvoice: ["ServiceInvoice"],
    models.Party: ["Party.borrower", "Party.provider"],
    models.Company: ["Company"],
    models.Certificate: ["Certificate"],
    models.Webhook: ["Webhook"],
    models.WebhookEventType: ["WebhookEventType"],
    models.LegalEntity: ["LegalEntity"],
    models.NaturalPerson: ["NaturalPerson"],
    models.Address: ["Address"],
}

#: TypedDict -> (schema, must be complete?)
PARAM_SCHEMAS: dict[Any, tuple[str, bool]] = {
    types.ServiceInvoiceCreateParams: ("ServiceInvoiceCreateParams", True),
    types.BorrowerParams: ("BorrowerParams", True),
    types.AddressParams: ("AddressParams", True),
    types.CityParams: ("CityParams", True),
    types.CompanyParams: ("CompanyParams", True),
    types.CompanyAddressParams: ("CompanyAddressParams", True),
    # createdOn/modifiedOn are read-only; headers/properties are undocumented on the wire.
    types.WebhookParams: ("WebhookParams", False),
}


@pytest.mark.parametrize("model", list(MODEL_SCHEMAS), ids=lambda m: m.__name__)
def test_typed_properties_point_to_spec_keys(model: type[NfeObject]) -> None:
    allowed: set[str] = set()
    for schema in MODEL_SCHEMAS[model]:
        allowed |= set(SPEC_KEYS[schema])
    allowed |= set(PROVEN_DIVERGENCES.get(model.__name__, {}))
    fields = list(iter_fields(model))
    assert fields, model
    for name, field in fields:
        for key in field.wire_keys:
            assert key in allowed, f"{model.__name__}.{name} -> {key!r} is not in the spec"


def test_every_model_is_checked() -> None:
    public = {
        obj
        for obj in vars(models).values()
        if isinstance(obj, type) and issubclass(obj, NfeObject) and obj is not NfeObject
    }
    assert public == set(MODEL_SCHEMAS)


@pytest.mark.parametrize("typed", list(PARAM_SCHEMAS), ids=lambda t: t.__name__)
def test_request_typeddicts_match_spec(typed: Any) -> None:
    schema, complete = PARAM_SCHEMAS[typed]
    spec = set(SPEC_KEYS[schema])
    mine = set(typed.__annotations__)
    assert mine <= spec, f"{typed.__name__} has keys not in the spec: {sorted(mine - spec)}"
    if complete:
        assert mine == spec, f"{typed.__name__} misses spec keys: {sorted(spec - mine)}"


def test_phantom_property_is_detected() -> None:
    from nfeio.models._base import StrField

    class Phantom(models.ServiceInvoice):
        __slots__ = ()
        total_amount = StrField("totalAmount")  # the classic phantom field

    allowed = set(SPEC_KEYS["ServiceInvoice"])
    missing = [f.key for _, f in iter_fields(Phantom) if f.key not in allowed]
    assert missing == ["totalAmount"]


@pytest.mark.skipif(
    not (ROOT / "nfeio-docs" / "static" / "api" / "nf-servico-v1.yaml").exists(),
    reason="nfeio-docs checkout not available (snapshot is used instead)",
)
def test_snapshot_is_fresh() -> None:
    result = subprocess.run(  # noqa: S603 - fixed arguments
        [sys.executable, str(ROOT / "scripts" / "spec_keys.py"), "--check"],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
